query GetSkills($searchTerm: String = "", $limit: Int = 10, $offset: Int = 0)  @auth
(level: PUBLIC insecureReason: "Skills should be visible to everyone"){
    skills(
        where:  {
           _or: [ 
            { title:  { contains: $searchTerm }}
            { description: {contains: $searchTerm }}
           ] 
        },
        orderBy: [{
         createdAt: DESC
        }],
        limit: $limit
    ){
      id title description tags createdAt installCommand
      author { username imageUrl clerkId email }
    }
}

query GetSkillById($id: UUID!) @auth(level: PUBLIC insecureReason: "Skills should be visible to everyone") {
  skill(id: $id) {
    id title description tags installCommand promptConfig usageExample createdAt
    author { username imageUrl clerkId email }
  }
}